
-- 1. ENUMS
DO $$ BEGIN
    CREATE TYPE user_role AS ENUM ('docente', 'supervisor', 'admin');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE incident_type AS ENUM ('estudiante', 'aula', 'general');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE incident_status AS ENUM ('registrada', 'leída', 'atención', 'resuelta');
EXCEPTION WHEN duplicate_object THEN null; END $$;

DO $$ BEGIN
    CREATE TYPE school_level AS ENUM ('inicial', 'primaria', 'secundaria');
EXCEPTION WHEN duplicate_object THEN null; END $$;

-- 2. TABLAS
CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT NOT NULL,
  role user_role NOT NULL DEFAULT 'docente',
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS incident_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS incidents (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  correlative TEXT UNIQUE, 
  incident_date TIMESTAMPTZ NOT NULL DEFAULT now(),
  type incident_type NOT NULL,
  level school_level,
  grade TEXT,
  section TEXT,
  room_name TEXT,
  category_id BIGINT REFERENCES incident_categories(id),
  other_category_suggestion TEXT,
  description TEXT NOT NULL,
  teacher_id UUID NOT NULL REFERENCES profiles(id),
  image_url TEXT,
  involved_students JSONB DEFAULT '[]'::jsonb,
  status incident_status DEFAULT 'registrada',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. TRIGGER CORRELATIVO
CREATE SEQUENCE IF NOT EXISTS incident_correlative_seq;

CREATE OR REPLACE FUNCTION generate_incident_correlative()
RETURNS TRIGGER AS $$
DECLARE
  current_year TEXT := to_char(now(), 'YYYY');
  next_val BIGINT;
BEGIN
  SELECT nextval('incident_correlative_seq') INTO next_val;
  NEW.correlative := 'INC-' || current_year || '-' || LPAD(next_val::TEXT, 6, '0');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tr_generate_correlative ON incidents;
CREATE TRIGGER tr_generate_correlative
BEFORE INSERT ON incidents
FOR EACH ROW
EXECUTE FUNCTION generate_incident_correlative();

-- 4. SEGURIDAD (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE incident_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE incidents ENABLE ROW LEVEL SECURITY;

-- Políticas de Incidencias
DROP POLICY IF EXISTS "Ver Incidencias" ON incidents;
CREATE POLICY "Ver Incidencias" ON incidents FOR SELECT 
TO authenticated 
USING (teacher_id = auth.uid() OR (SELECT role FROM profiles WHERE id = auth.uid()) IN ('supervisor', 'admin'));

DROP POLICY IF EXISTS "Insertar Incidencias" ON incidents;
CREATE POLICY "Insertar Incidencias" ON incidents FOR INSERT 
TO authenticated 
WITH CHECK (teacher_id = auth.uid());

DROP POLICY IF EXISTS "Actualizar Incidencias" ON incidents;
CREATE POLICY "Actualizar Incidencias" ON incidents FOR UPDATE 
TO authenticated 
USING ((SELECT role FROM profiles WHERE id = auth.uid()) IN ('supervisor', 'admin'));

-- 5. SEED DATA (Categorías iniciales)
INSERT INTO incident_categories (name) VALUES 
('Conducta Inapropiada'),
('Conflicto entre Pares (Agresión)'),
('Uso Indebido de Dispositivos'),
('Daño a Infraestructura / Mobiliario'),
('Incumplimiento de Tareas/Materiales'),
('Tardanza / Fuga de Clase'),
('Salud / Emergencia Médica'),
('Otro (Sugerencia de Docente)')
ON CONFLICT (name) DO NOTHING;
