import React, { useState, useEffect } from 'react';
import { supabase } from '../supabase';
import { UserRole, Profile, SchoolLevel } from '../types';
import { Shield, ShieldAlert, ShieldCheck, Mail, UserPlus, Loader2, Database, Copy, CheckCircle, AlertCircle, Key, MapPin, Plus, X, Save } from 'lucide-react';

const UserManager: React.FC = () => {
  const [users, setUsers] = useState<Profile[]>([]);
  const [loading, setLoading] = useState(true);
  const [showSqlSetup, setShowSqlSetup] = useState(false);
  const [copied, setCopied] = useState(false);

  const [isSaving, setIsSaving] = useState(false);

  useEffect(() => {
    fetchUsers();
  }, []);

  const fetchUsers = async () => {
    setLoading(true);
    const { data } = await supabase.from('profiles').select('*').order('full_name', { ascending: true });
    if (data) setUsers(data as Profile[]);
    setLoading(false);
  };

  const handleToggleActive = async (id: string, currentStatus: boolean) => {
    try {
      const { error } = await supabase.rpc('toggle_profile_status', {
        target_user_id: id,
        new_status: !currentStatus
      });

      if (error) throw error;
      fetchUsers();
    } catch (err: any) {
      console.error('Error toggling status:', err);
      alert('Error al cambiar estado: ' + err.message);
    }
  };



  const getRoleBadge = (role: UserRole) => {
    switch (role) {
      case UserRole.ADMIN: return <div className="flex items-center space-x-1 px-2.5 py-1 bg-purple-100 text-purple-700 rounded-full text-[10px] font-black uppercase"><ShieldAlert className="w-3 h-3" /><span>Admin</span></div>;
      case UserRole.SUPERVISOR: return <div className="flex items-center space-x-1 px-2.5 py-1 bg-blue-100 text-blue-700 rounded-full text-[10px] font-black uppercase"><ShieldCheck className="w-3 h-3" /><span>Supervisor</span></div>;
      case UserRole.SECRETARIA: return <div className="flex items-center space-x-1 px-2.5 py-1 bg-amber-100 text-amber-700 rounded-full text-[10px] font-black uppercase"><ShieldCheck className="w-3 h-3" /><span>Secretaria</span></div>;
      default: return <div className="flex items-center space-x-1 px-2.5 py-1 bg-gray-100 text-gray-700 rounded-full text-[10px] font-black uppercase"><Shield className="w-3 h-3" /><span>Docente</span></div>;
    }
  };

  const sqlCode = `-- 1. ACCESO MAESTRO (Darte rol de Admin)
-- Reemplaza el correo por el tuyo y ejecútalo después de registrarte:
UPDATE profiles 
SET role = 'admin' 
WHERE id IN (SELECT id FROM auth.users WHERE email = 'tu-correo@ejemplo.com');

-- 2. TABLAS E INFRAESTRUCTURA (Ejecutar una sola vez)
CREATE TYPE user_role AS ENUM ('docente', 'secretaria', 'supervisor', 'admin');
CREATE TYPE incident_type AS ENUM ('estudiante', 'aula', 'general');
CREATE TYPE incident_status AS ENUM ('registrada', 'leída', 'atención', 'resuelta');
CREATE TYPE school_level AS ENUM ('inicial', 'primaria', 'secundaria');

CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT NOT NULL,
  role user_role NOT NULL DEFAULT 'docente',
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS incident_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS incidents (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  correlative TEXT UNIQUE, 
  incident_date TIMESTAMPTZ NOT NULL DEFAULT now(),
  type incident_type NOT NULL,
  level school_level NOT NULL,
  grade TEXT NOT NULL,
  section TEXT NOT NULL,
  category_id BIGINT REFERENCES incident_categories(id),
  description TEXT NOT NULL,
  teacher_id UUID NOT NULL REFERENCES profiles(id),
  status incident_status DEFAULT 'registrada',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Autocorrrelativo Trigger
CREATE SEQUENCE IF NOT EXISTS incident_correlative_seq;
CREATE OR REPLACE FUNCTION generate_incident_correlative() RETURNS TRIGGER AS $$
BEGIN
  NEW.correlative := 'INC-' || to_char(now(), 'YYYY') || '-' || LPAD(nextval('incident_correlative_seq')::TEXT, 6, '0');
  RETURN NEW;
END; $$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS tr_generate_correlative ON incidents;
CREATE TRIGGER tr_generate_correlative BEFORE INSERT ON incidents FOR EACH ROW EXECUTE FUNCTION generate_incident_correlative();

-- Perfil automático
CREATE OR REPLACE FUNCTION public.handle_new_user() RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, role)
  VALUES (new.id, COALESCE(new.raw_user_meta_data->>'full_name', new.email), 'docente');
  RETURN new;
END; $$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();`;

  const copyToClipboard = () => {
    navigator.clipboard.writeText(sqlCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const [showAddUser, setShowAddUser] = useState(false);
  const [newUser, setNewUser] = useState({
    email: '',
    password: '',
    fullName: '',
    role: 'docente' as UserRole
  });
  const [creating, setCreating] = useState(false);

  const handleAddUser = async (e: React.FormEvent) => {
    e.preventDefault();
    setCreating(true);

    try {
      const { error } = await supabase.rpc('create_new_user', {
        email: newUser.email,
        password: newUser.password,
        full_name: newUser.fullName,
        role_name: newUser.role
      });

      if (error) throw error;

      setShowAddUser(false);
      setNewUser({ email: '', password: '', fullName: '', role: 'docente' as UserRole });
      fetchUsers(); // Refresh list
      alert('Usuario creado exitosamente');
    } catch (err: any) {
      console.error('Error creating user:', err);
      alert('Error al crear usuario: ' + err.message);
    } finally {
      setCreating(false);
    }
  };

  return (
    <div className="space-y-10 max-w-6xl mx-auto animate-in fade-in duration-500 pb-20">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-6">
        <div>
          <h1 className="text-4xl font-black text-gray-800 tracking-tight">Gestión de Usuarios</h1>
          <p className="text-gray-400 font-medium">Control de acceso y perfiles institucionales</p>
        </div>
        <div className="flex space-x-3">
          <button
            onClick={() => setShowSqlSetup(!showSqlSetup)}
            className="p-4 rounded-2xl bg-gray-50 text-gray-400 hover:text-brand-turquoise hover:bg-white border-2 border-transparent hover:border-brand-turquoise transition-all"
            title="Acceso Maestro"
          >
            <Key className="w-6 h-6" />
          </button>
          <button
            onClick={() => setShowAddUser(true)}
            className="bg-brand-turquoise text-white px-8 py-4 rounded-2xl font-black text-sm shadow-xl shadow-brand-turquoise/20 flex items-center space-x-2 hover:bg-brand-darkTurquoise transition-all"
          >
            <Plus className="w-5 h-5" />
            <span>Agregar Usuario</span>
          </button>
        </div>
      </div>

      {/* MODAL AGREGAR USUARIO */}
      {showAddUser && (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4 animate-in fade-in duration-200">
          <div className="bg-white rounded-[2.5rem] w-full max-w-lg overflow-hidden shadow-2xl animate-in zoom-in-95 duration-200">
            <div className="bg-brand-turquoise p-8 text-white flex justify-between items-center">
              <h2 className="text-xl font-black flex items-center space-x-2">
                <UserPlus className="w-6 h-6" />
                <span>Nuevo Usuario</span>
              </h2>
              <button type="button" onClick={() => setShowAddUser(false)} className="hover:bg-white/20 p-2 rounded-full transition-colors">
                <X className="w-5 h-5" />
              </button>
            </div>

            <form onSubmit={handleAddUser} className="p-8 space-y-6">
              <div className="space-y-2">
                <label className="text-xs font-black text-gray-400 uppercase tracking-widest pl-1">Nombre Completo</label>
                <input
                  required
                  type="text"
                  className="w-full px-4 py-3 rounded-xl border-2 border-gray-100 bg-gray-50 focus:bg-white focus:border-brand-turquoise outline-none font-bold text-gray-700 transition-all"
                  placeholder="Ej. María Sánchez"
                  value={newUser.fullName}
                  onChange={e => setNewUser({ ...newUser, fullName: e.target.value })}
                />
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <label className="text-xs font-black text-gray-400 uppercase tracking-widest pl-1">Correo</label>
                  <input
                    required
                    type="email"
                    className="w-full px-4 py-3 rounded-xl border-2 border-gray-100 bg-gray-50 focus:bg-white focus:border-brand-turquoise outline-none font-bold text-gray-700 transition-all"
                    placeholder="usuario@colegio.edu.pe"
                    value={newUser.email}
                    onChange={e => setNewUser({ ...newUser, email: e.target.value })}
                  />
                </div>
                <div className="space-y-2">
                  <label className="text-xs font-black text-gray-400 uppercase tracking-widest pl-1">Contraseña</label>
                  <input
                    required
                    type="password"
                    className="w-full px-4 py-3 rounded-xl border-2 border-gray-100 bg-gray-50 focus:bg-white focus:border-brand-turquoise outline-none font-bold text-gray-700 transition-all"
                    placeholder="••••••••"
                    value={newUser.password}
                    onChange={e => setNewUser({ ...newUser, password: e.target.value })}
                  />
                </div>
              </div>

              <div className="space-y-2">
                <label className="text-xs font-black text-gray-400 uppercase tracking-widest pl-1">Rol Asignado</label>
                <div className="grid grid-cols-3 gap-3">
                  {(['docente', 'secretaria', 'supervisor', 'admin'] as const).map((role) => (
                    <button
                      key={role}
                      type="button"
                      onClick={() => setNewUser({ ...newUser, role: role as UserRole })}
                      className={`py-3 rounded-xl text-[10px] font-black uppercase tracking-widest border-2 transition-all ${newUser.role === role
                        ? 'border-brand-turquoise bg-brand-turquoise/10 text-brand-turquoise'
                        : 'border-gray-100 bg-gray-50 text-gray-400 hover:border-gray-200'
                        }`}
                    >
                      {role === 'docente' ? 'Docente' : role === 'secretaria' ? 'Secretaria' : role === 'supervisor' ? 'Superv.' : 'Admin'}
                    </button>
                  ))}
                </div>
              </div>

              <div className="pt-4 flex gap-4">
                <button
                  type="button"
                  onClick={() => setShowAddUser(false)}
                  className="flex-1 py-4 rounded-xl font-black text-xs uppercase tracking-widest text-gray-400 hover:bg-gray-100 transition-all"
                >
                  Cancelar
                </button>
                <button
                  type="submit"
                  disabled={creating}
                  className="flex-1 py-4 rounded-xl font-black text-xs uppercase tracking-widest bg-brand-turquoise text-white hover:bg-brand-darkTurquoise shadow-lg shadow-brand-turquoise/20 transition-all disabled:opacity-50 flex items-center justify-center gap-2"
                >
                  {creating ? <Loader2 className="w-4 h-4 animate-spin" /> : <UserPlus className="w-4 h-4" />}
                  <span>{creating ? 'Creando...' : 'Crear Usuario'}</span>
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {showSqlSetup && (
        <div className="bg-white border-2 border-brand-turquoise rounded-[2.5rem] overflow-hidden shadow-2xl animate-in slide-in-from-top-4 duration-300 mb-12">
          <div className="bg-brand-turquoise p-8 text-white">
            <h2 className="text-2xl font-black flex items-center space-x-3">
              <Database className="w-8 h-8" />
              <span>Instrucciones de Acceso Maestro</span>
            </h2>
            <p className="text-white/80 mt-2 font-medium">Copia este código para darte permisos de Administrador en el SQL Editor de Supabase:</p>
          </div>
          <div className="p-10 space-y-8">
            <div className="relative group">
              <pre className="bg-gray-900 text-emerald-400 p-8 rounded-3xl text-xs overflow-x-auto font-mono leading-relaxed max-h-[400px]">
                {sqlCode}
              </pre>
              <button
                onClick={copyToClipboard}
                className="absolute top-6 right-6 bg-white/10 hover:bg-white/20 text-white px-4 py-2 rounded-xl backdrop-blur-md flex items-center space-x-2 transition-all border border-white/10"
              >
                {copied ? <CheckCircle className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
                <span className="text-[10px] font-black uppercase tracking-widest">{copied ? 'Copiado' : 'Copiar Script'}</span>
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Content Area */}
      {loading ? (
        <div className="py-20 flex flex-col items-center">
          <Loader2 className="w-12 h-12 text-brand-turquoise animate-spin" />
          <p className="mt-4 text-[10px] font-black text-gray-400 uppercase tracking-widest">Cargando Usuarios...</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {users.map(u => (
            <div key={u.id} className="bg-white p-8 rounded-[2rem] border border-gray-100 shadow-xl shadow-gray-200/40 hover:-translate-y-1 transition-all group">
              <div className="flex items-start justify-between mb-6">
                <div className="w-16 h-16 bg-brand-light rounded-2xl flex items-center justify-center text-brand-turquoise font-black text-2xl group-hover:scale-110 transition-transform uppercase">
                  {u.full_name?.charAt(0)}
                </div>
                {getRoleBadge(u.role)}
              </div>
              <h3 className="font-black text-xl text-gray-800 tracking-tight truncate">{u.full_name}</h3>
              <div className="flex flex-col space-y-1 mt-2">
                <div className="flex items-center space-x-2 text-gray-500 text-[10px] font-bold uppercase tracking-wider">
                  <Mail className="w-3 h-3" />
                  <span className="truncate">{u.email || 'Sin correo sync'}</span>
                </div>
                <div className="flex items-center space-x-2 text-gray-400 text-[9px] font-medium tracking-tight">
                  <Database className="w-3 h-3" />
                  <span className="truncate">ID: {u.id.substring(0, 15)}...</span>
                </div>
              </div>

              <div className="mt-8 pt-8 border-t border-gray-50 flex items-center justify-between">
                <div className="text-[10px] font-black text-gray-400 uppercase tracking-widest pl-1">
                  Control Acceso
                </div>
                <button
                  onClick={() => handleToggleActive(u.id, u.active || false)}
                  className={`text-xs font-black uppercase tracking-widest ${u.active ? 'text-red-500 hover:underline' : 'text-emerald-500'}`}
                >
                  {u.active ? 'Desactivar' : 'Activar'}
                </button>
              </div>
            </div>
          ))}
        </div>
      )}



    </div>
  );
};

export default UserManager;
